<%@ page language="C#" autoeventwireup="true" CodeFile="Default4.aspx.cs" Inherits="Default4" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>VERIFICATION SAISIE</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <a href="Default.aspx" >MENU</a>
            <br />
            <br />
            <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" Font-Names="Lucida Console" Font-Size="Larger">
                <asp:ListItem Selected="True">&nbsp;</asp:ListItem>
                <asp:ListItem Value="ALL"> Toutes les Series </asp:ListItem>
                <asp:ListItem Value="J1"> Jour 1</asp:ListItem>
                <asp:ListItem Value="J2"> Jour 2</asp:ListItem>
                <asp:ListItem Value="J3"> Jour 3</asp:ListItem>
            </asp:DropDownList>
            <table border="0">
            <tr><td valign="top">
            <asp:GridView Visible="true" ID="G_S1" runat="server" DataSourceID="S1" 
                Caption="JOUR 1 - SERIE 1" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_S2" runat="server" DataSourceID="S2" 
                Caption="JOUR 1 - SERIE 2" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_S3" runat="server" DataSourceID="S3" 
                Caption="JOUR 1 - SERIE 3" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_D1" runat="server" DataSourceID="D1" 
                Caption="JOUR 2 - SERIE 1" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_D2" runat="server" DataSourceID="D2" 
                Caption="JOUR 2 - SERIE 2" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_D3" runat="server" DataSourceID="D3" 
                Caption="JOUR 2 - SERIE 3" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_L1" runat="server" DataSourceID="L1" 
                Caption="JOUR 3 - SERIE 1" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_L2" runat="server" DataSourceID="L2" 
                Caption="JOUR 3 - SERIE 2" />
            </td><td valign="top">
            <asp:GridView Visible="true" ID="G_L3" runat="server" DataSourceID="L3" 
                Caption="JOUR 3 - SERIE 3" />
             </td>
            </tr></table>
            <asp:SqlDataSource ID="S1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 1 SET @JOUR = 1 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="S2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 2 SET @JOUR = 1 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="S3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 3 SET @JOUR = 1 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="D1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 1 SET @JOUR = 2 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="D2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 2 SET @JOUR = 2 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="D3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 3 SET @JOUR = 2 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="L1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 1 SET @JOUR = 3 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="L2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 2 SET @JOUR = 3 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="L3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="DECLARE @SERIE INTEGER DECLARE @JOUR INTEGER SET @SERIE = 3 SET @JOUR = 3 SELECT NUMERO, JURY, CASE WHEN MAX(CASE WHEN JURE=1 THEN 1 ELSE 0 END)=0 THEN '1' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=2 THEN 1 ELSE 0 END)=0 THEN '2' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=3 THEN 1 ELSE 0 END)=0 THEN '3' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=4 THEN 1 ELSE 0 END)=0 THEN '4' ELSE '_' END + CASE WHEN MAX(CASE WHEN JURE=5 THEN 1 ELSE 0 END)=0 THEN '5' ELSE '_' END As JURE_MANQUANT INTO #TABLE FROM SAISIE_SERIE where JOUR =@JOUR AND SERIE = @SERIE GROUP BY NUMERO, JURY HAVING COUNT(*) <> 5 ORDER BY NUMERO, JURY INSERT INTO #TABLE SELECT ORDRE, JURY, '12345' FROM LISTE_VINS where LISTE_VINS.SERIE = @SERIE AND   LISTE_VINS.JOUR = @JOUR AND ORDRE NOT IN (SELECT NUMERO FROM SAISIE_SERIE  WHERE SAISIE_SERIE.JOUR =@JOUR AND SAISIE_SERIE.SERIE = @SERIE) GROUP BY ORDRE, JURY SELECT JURY, NUMERO, JURE_MANQUANT FROM #TABLE ORDER BY JURY, NUMERO DROP TABLE #TABLE">
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
