using System;
using System.Data.SqlClient;
using System.Web;
using System.Web.Profile;
using System.Web.SessionState;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

public partial class Default5 : Page, IRequiresSessionState
{
    //protected Button Button1;
    //protected HtmlForm form1;

    protected void Button1_Click(object sender, EventArgs e)
    {
        string connectionString = System.Web.Configuration.WebConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
        using (SqlCommand command = new SqlCommand("DELETE FROM PRECALCUL INSERT INTO PRECALCUL SELECT MAX(LISTE_VINS.[ORDRE]) ,AVG(CAST(SAISIE_SERIE.[TOTAL] AS FLOAT)) ,ROUND(STDEV(CAST(SAISIE_SERIE.[TOTAL] AS FLOAT)),2) /*,AVG(CAST(SAISIE_SERIE.[APPRECIATION] AS FLOAT))*/ ,MAX(LISTE_VINS.[JURY]) ,MAX (CASE WHEN SAISIE_SERIE.JURE=1 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=2 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=3 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=4 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=5 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX(LISTE_VINS.[SERIE]) ,MAX(LISTE_VINS.[RANG]) ,MAX(LISTE_VINS.CATEGORIE) ,MAX(LISTE_VINS.PAYS) ,MAX(LISTE_VINS.[CODE REGION]) ,MAX(LISTE_VINS.[CODE APPELLATION]) ,MAX(LISTE_VINS.[APPELLATION]) ,MAX(LISTE_VINS.[MILLESIME]) ,MAX(LISTE_VINS.[FIRME]) ,MAX(LISTE_VINS.[NOM]) ,NULL ,MAX(LISTE_VINS.[CRU OU MARQUE]) ,MAX(LISTE_VINS.[CAB]) ,NULL ,MAX(LISTE_VINS.[VOLUME]) ,MAX(LISTE_VINS.[CEPAGE]) ,MAX(SAISIE_SERIE.[JOUR]),SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT01] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT02] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT03] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT04] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT05] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT06] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT07] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT08] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT09] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT10] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT11] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT12] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT13] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT14] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT15] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT16] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT17] AS INT),0)) ,SUM(CASE WHEN N11 IS NULL THEN  N3*7 ELSE N4*6 END) ,SUM(CASE WHEN N11 IS NULL THEN  N4*7 ELSE N5*6 END) ,SUM(CASE WHEN N11 IS NULL THEN  N5*14 ELSE N6*16 END) ,SUM(CASE WHEN N11 IS NULL THEN  N6*7 ELSE N7*6 END) ,SUM(CASE WHEN N11 IS NULL THEN  N7*7 ELSE N8*8 END) ,SUM(CASE WHEN N11 IS NULL THEN  N8*7 ELSE N9*8 END) ,SUM(CASE WHEN N11 IS NULL THEN  N9*14 ELSE N10*22 END) ,SUM(CASE WHEN N11 IS NULL THEN  N10*12 ELSE N11*11 END) FROM (SELECT DISTINCT * FROM LISTE_VINS) LISTE_VINS, (SELECT DISTINCT * FROM SAISIE_SERIE) SAISIE_SERIE WHERE LISTE_VINS.ORDRE = SAISIE_SERIE.NUMERO GROUP BY SAISIE_SERIE.NUMERO"))
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                command.Connection = connection;
                command.ExecuteNonQuery().ToString();
                connection.Close();
            }
        }
    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        string connectionString = System.Web.Configuration.WebConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
//        using (SqlCommand command = new SqlCommand("DELETE FROM PRECALCUL INSERT INTO PRECALCUL SELECT MAX(LISTE_VINS.[ORDRE]) ,AVG(CAST(SAISIE_SERIE.[TOTAL] AS FLOAT)) ,ROUND(STDEV(CAST(SAISIE_SERIE.[TOTAL] AS FLOAT)),2) ,AVG(CAST(SAISIE_SERIE.[APPRECIATION] AS FLOAT)) ,MAX(LISTE_VINS.[JURY]) ,MAX (CASE WHEN SAISIE_SERIE.JURE=1 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=2 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=3 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=4 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=5 THEN SAISIE_SERIE.[TOTAL] ELSE 0 END) ,MAX(LISTE_VINS.[SERIE]) ,MAX(LISTE_VINS.[RANG]) ,MAX(LISTE_VINS.CATEGORIE) ,MAX(LISTE_VINS.PAYS) ,MAX(LISTE_VINS.[CODE REGION]) ,MAX(LISTE_VINS.[CODE APPELLATION]) ,MAX(LISTE_VINS.[APPELLATION]) ,MAX(LISTE_VINS.[MILLESIME]) ,MAX(LISTE_VINS.[FIRME]) ,MAX(LISTE_VINS.[NOM]) ,NULL ,MAX(LISTE_VINS.[CRU OU MARQUE]) ,MAX(LISTE_VINS.[CAB]) ,NULL ,MAX(LISTE_VINS.[VOLUME]) ,MAX(LISTE_VINS.[CEPAGE]) ,MAX(SAISIE_SERIE.[JOUR]) FROM (SELECT * FROM LISTE_VINS) LISTE_VINS, ( SELECT * FROM (SELECT SAISIE_SERIE.*, ROW_NUMBER() OVER(PARTITION BY SAISIE_SERIE.NUMERO ORDER BY ABS(SAISIE_SERIE.TOTAL - TAB.TOTAL) DESC,SAISIE_SERIE.TOTAL) RANG FROM ( 	SELECT ROW_NUMBER() OVER(PARTITION BY NUMERO ORDER BY TOTAL) RANG, NUMERO, TOTAL FROM SAISIE_SERIE ) TAB, SAISIE_SERIE WHERE TAB.RANG = 3 AND SAISIE_SERIE.NUMERO = TAB.NUMERO ) TAB2 WHERE RANG > 1) SAISIE_SERIE WHERE LISTE_VINS.ORDRE = SAISIE_SERIE.NUMERO GROUP BY SAISIE_SERIE.NUMERO"))
        using (SqlCommand command = new SqlCommand("DELETE FROM PRECALCUL INSERT INTO PRECALCUL SELECT MAX(LISTE_VINS.[ORDRE]) ,AVG(CAST(SAISIE_SERIE.[TOTAL] AS FLOAT)) ,ROUND(STDEV(CAST(SAISIE_SERIE.[TOTAL] AS FLOAT)),2) /*,AVG(CAST(SAISIE_SERIE.[APPRECIATION] AS FLOAT))*/ ,MAX(LISTE_VINS.[JURY]) ,MAX (CASE WHEN SAISIE_SERIE.JURE=1 THEN SAISIE_SERIE.[TOTAL] ELSE -1 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=2 THEN SAISIE_SERIE.[TOTAL] ELSE -1 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=3 THEN SAISIE_SERIE.[TOTAL] ELSE -1 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=4 THEN SAISIE_SERIE.[TOTAL] ELSE -1 END) ,MAX (CASE WHEN SAISIE_SERIE.JURE=5 THEN SAISIE_SERIE.[TOTAL] ELSE -1 END) ,MAX(LISTE_VINS.[SERIE]) ,MAX(LISTE_VINS.[RANG]) ,MAX(LISTE_VINS.CATEGORIE) ,MAX(LISTE_VINS.PAYS) ,MAX(LISTE_VINS.[CODE REGION]) ,MAX(LISTE_VINS.[CODE APPELLATION]) ,MAX(LISTE_VINS.[APPELLATION]) ,MAX(LISTE_VINS.[MILLESIME]) ,MAX(LISTE_VINS.[FIRME]) ,MAX(LISTE_VINS.[NOM]) ,NULL ,MAX(LISTE_VINS.[CRU OU MARQUE]) ,MAX(LISTE_VINS.[CAB]) ,NULL ,MAX(LISTE_VINS.[VOLUME]) ,MAX(LISTE_VINS.[CEPAGE]) ,MAX(SAISIE_SERIE.[JOUR]),SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT01] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT02] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT03] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT04] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT05] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT06] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT07] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT08] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT09] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT10] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT11] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT12] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT13] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT14] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT15] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT16] AS INT),0)) ,SUM(ISNULL(CAST(SAISIE_SERIE.[CRIT17] AS INT),0)) ,SUM(CASE WHEN N11 IS NULL THEN  N3*7 ELSE N4*6 END) ,SUM(CASE WHEN N11 IS NULL THEN  N4*7 ELSE N5*6 END) ,SUM(CASE WHEN N11 IS NULL THEN  N5*14 ELSE N6*16 END) ,SUM(CASE WHEN N11 IS NULL THEN  N6*7 ELSE N7*6 END) ,SUM(CASE WHEN N11 IS NULL THEN  N7*7 ELSE N8*8 END) ,SUM(CASE WHEN N11 IS NULL THEN  N8*7 ELSE N9*8 END) ,SUM(CASE WHEN N11 IS NULL THEN  N9*14 ELSE N10*22 END) ,SUM(CASE WHEN N11 IS NULL THEN  N10*12 ELSE N11*11 END) FROM (SELECT * FROM LISTE_VINS) LISTE_VINS, ( SELECT * FROM (SELECT SAISIE_SERIE.*, ROW_NUMBER() OVER(PARTITION BY SAISIE_SERIE.NUMERO ORDER BY ABS(SAISIE_SERIE.TOTAL - TAB.TOTAL) DESC,SAISIE_SERIE.TOTAL) RANG FROM ( 	SELECT ROW_NUMBER() OVER(PARTITION BY NUMERO ORDER BY TOTAL) RANG, NUMERO, TOTAL FROM SAISIE_SERIE ) TAB, SAISIE_SERIE WHERE TAB.RANG = 3 AND SAISIE_SERIE.NUMERO = TAB.NUMERO ) TAB2 WHERE RANG > 1) SAISIE_SERIE WHERE LISTE_VINS.ORDRE = SAISIE_SERIE.NUMERO GROUP BY SAISIE_SERIE.NUMERO"))
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                command.Connection = connection;
                command.ExecuteNonQuery().ToString();
                connection.Close();
            }
        }
    }

    protected void Page_Load(object sender, EventArgs e)
    {
    }

   

}

